# Generated by Django 4.0.1 on 2022-04-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedv2', '0002_rename_section_section_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='NA', max_length=512),
            preserve_default=False,
        ),
    ]
